### ISSUE TITLE
Impossible to remove submission

### ISSUE THREAD

**Issue by thepurpleblob** [MaharaProject/moodle-assignsubmission_mahara#38]
Student makes a submission and then changes their mind. They click 'Remove submission' and confirm the acknowledgment screen. Nothing happens - it returns to the previous screen.

I have run with debugging on and nothing is shown or logged.

**Comment by agarnav** [comment]
Hi, we have the same error and we have run the same debugging. We use phis plugin since 2013 and this year we will be using this plugin on a large scale.
So, could you correct this error. Thank you

**Comment by anitsirk** [comment]
This would be a new feature as it had never been implemented to remove the submission. This plugin is no longer receiving new features from us as maintainers because we are focusing on the [web services edition of this plugin](https://github.com/catalyst/moodle-assignsubmission_maharaws). We'd be happy to look into this for you though if you'd like to sponsor this feature, @agarnav .

**Comment by agarnav** [comment]
Thanks for your answer, Kristina. I understand ant I will try install web services and test ( our versions  MAHARA and MOODLE are corrects). So if  MNET  protocol  is not maintained, we will be ready. We think it's better. Maybe a future contribution for the French Moodlemoot in my university in July 2022 ... best regards

**Comment by anitsirk** [comment]
@agarnav that sounds good. Web services already come with Mahara as does the LTI 1.1 integration. So there is no plugin needed on the Mahara end. It's only Moodle that would require the plugin. All the best.
